package dev.gaphunter.piitostringleakcompanion.detect

import com.intellij.psi.JavaRecursiveElementWalkingVisitor
import com.intellij.psi.JavaTokenType
import com.intellij.psi.PsiClass
import com.intellij.psi.PsiClassType
import com.intellij.psi.PsiElement
import com.intellij.psi.PsiExpression
import com.intellij.psi.PsiFile
import com.intellij.psi.PsiMethodCallExpression
import com.intellij.psi.PsiPolyadicExpression
import com.intellij.psi.PsiReferenceExpression
import dev.gaphunter.piitostringleakcompanion.model.PiiToStringHit

/**
 * Finds a logging/print call passed an instance of a class whose
 * `toString()` exposes a PII field, without explicit field selection
 * -- `toString()` on a user object often serializes the whole model,
 * including email/phone/SSN, unlike `log.info(user.getEmail())` which
 * explicitly picks only what should be logged. A well-documented
 * pattern of real incidents (Piiano, New Relic, Guidewire Security).
 *
 * **Different angle from `pii-field-annotation-companion`** (this
 * catalog): that plugin flags a PII field itself passed directly to a
 * logger; here the field never appears textually at the call site at
 * all -- it leaks implicitly through `toString()`'s serialization of
 * the whole object.
 *
 * **v0.1 scope, stated honestly:** only `toString()` generated by the
 * IDE or Lombok `@ToString` (see [PiiToStringClassResolver]) -- a
 * fully hand-written `toString()` with arbitrary logic is out of
 * scope. Also covers implicit string concatenation
 * (`log.info("User: " + user)`), not just a direct single argument.
 */
object JavaPiiToStringFinder {

    fun findAll(file: PsiFile): List<PiiToStringHit> {
        val hits = mutableListOf<PiiToStringHit>()
        val classCache = mutableMapOf<PsiClass, String?>()

        file.accept(object : JavaRecursiveElementWalkingVisitor() {
            override fun visitMethodCallExpression(call: PsiMethodCallExpression) {
                super.visitMethodCallExpression(call)
                if (!LoggingCallSignals.isLoggingCall(call) && !LoggingCallSignals.isPrintlnCall(call)) return

                val firstArg = call.argumentList.expressions.getOrNull(0) ?: return
                for (candidate in flattenConcatOperands(firstArg)) {
                    val reference = candidate as? PsiReferenceExpression ?: continue
                    val classType = reference.type as? PsiClassType ?: continue
                    val psiClass = classType.resolve() ?: continue
                    val piiField = classCache.getOrPut(psiClass) { PiiToStringClassResolver.exposedPiiField(psiClass) } ?: continue

                    hits += PiiToStringHit(anchorOf(call.methodExpression), psiClass.name ?: "?", piiField)
                }
            }
        })
        return hits
    }

    /** `log.info("User: " + user)` is a `PsiPolyadicExpression` with `+` -- each operand is a candidate; anything else is just itself. */
    private fun flattenConcatOperands(expression: PsiExpression): List<PsiExpression> {
        if (expression is PsiPolyadicExpression && expression.operationTokenType == JavaTokenType.PLUS) {
            return expression.operands.toList()
        }
        return listOf(expression)
    }

    private fun anchorOf(methodExpr: PsiReferenceExpression): PsiElement = methodExpr.referenceNameElement ?: methodExpr
}
