package dev.gaphunter.piitostringleakcompanion.detect

import com.intellij.psi.JavaRecursiveElementWalkingVisitor
import com.intellij.psi.PsiClass
import com.intellij.psi.PsiCodeBlock
import com.intellij.psi.PsiReferenceExpression

/**
 * Resolves whether a class's `toString()` exposes a PII field --
 * either a hand-written/IDE-generated `toString()` whose body
 * references the field's name, or Lombok's `@ToString` (which
 * includes every field by default unless individually marked
 * `@ToString.Exclude`).
 *
 * **v0.1 scope, stated honestly:** only `toString()` generated by the
 * IDE or by Lombok `@ToString` (a predictable field-listing shape) --
 * a `toString()` written completely by hand with arbitrary logic
 * (e.g. building a custom summary string) is out of scope; this
 * resolver can't tell "references the field" apart from "deliberately
 * omits it in a hand-crafted format", so it only trusts the two
 * predictable generation shapes.
 */
object PiiToStringClassResolver {

    /** The first PII field name exposed by [psiClass]'s `toString()`, or `null` if none is exposed (or no PII field exists at all). */
    fun exposedPiiField(psiClass: PsiClass): String? {
        val piiFields = psiClass.fields.filter { PiiFieldSignals.looksLikePii(it.name) }
        if (piiFields.isEmpty()) return null

        val toStringMethod = psiClass.methods.firstOrNull { it.name == "toString" && it.parameterList.parametersCount == 0 }
        val body = toStringMethod?.body
        if (body != null) {
            piiFields.firstOrNull { mentionsField(body, it.name) }?.let { return it.name }
        }

        val hasLombokToString = psiClass.annotations.any { it.nameReferenceElement?.referenceName == "ToString" }
        if (hasLombokToString) {
            piiFields.firstOrNull { field -> field.annotations.none { it.nameReferenceElement?.referenceName == "Exclude" } }
                ?.let { return it.name }
        }

        return null
    }

    private fun mentionsField(body: PsiCodeBlock, fieldName: String): Boolean {
        var found = false
        body.accept(object : JavaRecursiveElementWalkingVisitor() {
            override fun visitReferenceExpression(expression: PsiReferenceExpression) {
                if (found) return
                super.visitReferenceExpression(expression)
                if (expression.referenceName == fieldName) found = true
            }
        })
        return found
    }
}
